/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import quickpick.AccountPage;
import quickpick.AdminPage;
import quickpick.AppState;
import quickpick.EditProfilePage;
import quickpick.MainPage;
import quickpick.MainWindow;
import quickpick.ProductSellPage;
import quickpick.ProductWindow;
//import quickpick.SellProductPage;
import quickpick.TransactionPage;
import utility.Application;

/**
 *
 * @author Shreyas
 */
public class ProfileMenu extends javax.swing.JPanel {

    private AppState state;
    
    /**
     * Creates new form ProfileMenu
     */
    public ProfileMenu() {
        initComponents();
        
        btnAccount.addMouseListener(new FocusListener());
        btnEditProfile.addMouseListener(new FocusListener());
        btnSellProduct.addMouseListener(new FocusListener());
        btnTransactions.addMouseListener(new FocusListener());
        
        
        state = AppState.getInstance();
        
        // wait for user to be initialized
        new Thread(()->{
            try {
                while (state.user==null) {
                    Thread.sleep(100);
                }
                System.out.println("Got user : "+state.user);
                txtProfileName.setText(state.user.name);
                txtProfileEmail.setText(state.user.emailId);
                if (state.user.isAdmin) {
                    btnAdmin.addMouseListener(new FocusListener());
                    btnAdmin.setVisible(true);
                } else {
                    btnAdmin.setVisible(false);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            System.out.println("Thread that started in profileMenu ended");
        }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        txtProfileName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAccount = new javax.swing.JLabel();
        txtProfileEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEditProfile = new javax.swing.JLabel();
        btnSellProduct = new javax.swing.JLabel();
        btnTransactions = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(75, 75, 75));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtProfileName.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtProfileName.setForeground(new java.awt.Color(20, 20, 20));
        txtProfileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProfileName.setText("Name");

        btnAccount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(150, 150, 150));
        btnAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAccount.setText("Account");
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccountMouseClicked(evt);
            }
        });

        txtProfileEmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtProfileEmail.setForeground(new java.awt.Color(75, 75, 75));
        txtProfileEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProfileEmail.setText("email@id");

        btnEditProfile.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEditProfile.setForeground(new java.awt.Color(150, 150, 150));
        btnEditProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditProfileMouseClicked(evt);
            }
        });

        btnSellProduct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSellProduct.setForeground(new java.awt.Color(150, 150, 150));
        btnSellProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSellProduct.setText("Sell Product");
        btnSellProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSellProductMouseClicked(evt);
            }
        });

        btnTransactions.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnTransactions.setForeground(new java.awt.Color(150, 150, 150));
        btnTransactions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTransactions.setText("Transactions");
        btnTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransactionsMouseClicked(evt);
            }
        });

        btnAdmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(150, 150, 150));
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin.setText("Admin Page");
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(txtProfileEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProfileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSellProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransactions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        //JFrame frame = state.frame;
        state.frame.setVisible(false);
        MainPage window=new MainPage();
        //state.user=null;
        Application.goToFrame(window);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseClicked
        AccountPage window=new AccountPage();
        Application.goToFrame(window);
        //JOptionPane.showMessageDialog(null,"Account");
    }//GEN-LAST:event_btnAccountMouseClicked

    private void btnEditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditProfileMouseClicked
        EditProfilePage window=new EditProfilePage();
        Application.goToFrame(window);
        //JOptionPane.showMessageDialog(null,"Edit profile");
    }//GEN-LAST:event_btnEditProfileMouseClicked

    private void btnSellProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellProductMouseClicked
        ProductSellPage window=new ProductSellPage();
        Application.goToFrame(window);
        //JOptionPane.showMessageDialog(null,"Sell Product");
    }//GEN-LAST:event_btnSellProductMouseClicked

    private void btnTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransactionsMouseClicked
        TransactionPage window=new TransactionPage();
        Application.goToFrame(window);
        //JOptionPane.showMessageDialog(null,"Transaction");
    }//GEN-LAST:event_btnTransactionsMouseClicked

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        AdminPage window = new AdminPage();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnAdminMouseClicked


    class FocusListener implements MouseListener {
    
        @Override
        public void mouseEntered(MouseEvent e)
        {
            ((JLabel)e.getSource()).setForeground(new Color(0, 0, 0));//setBackground(new Color(200, 200, 200));
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mousePressed(MouseEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mouseExited(MouseEvent e) {
            ((JLabel)e.getSource()).setForeground(new Color(150, 150, 150));
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAccount;
    private javax.swing.JLabel btnAdmin;
    private javax.swing.JLabel btnEditProfile;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnSellProduct;
    private javax.swing.JLabel btnTransactions;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtProfileEmail;
    private javax.swing.JLabel txtProfileName;
    // End of variables declaration//GEN-END:variables
}
