/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickpick;

import components.CustomJTable;
import components.ProductPanel;
import database.Database;
import database.Heap;
import database.Product;
import database.User;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Application;
import utility.Graph;
import utility.Patterns;

/**
 *
 * @author Shreyas
 */
public class AdminPage extends javax.swing.JFrame {

    private AppState states;
    private Database database;
    public User user;
    private int wallpaperTime = 3*1000;
    private int wallpaperIndex = 0;
    private int wallpaperLength = 4;
    private boolean menuVisible = false;
    private String header[][]={{"Emaid Id","Name","Location","Contact Number","Rating","isAdmin"},/* user */
                               {"Product Id","Product Type","Product Name","Seller Id","Buyer Id","Date of upload","Date of selling","Discount","Price","Expiry"} /* products */};
    
    public AdminPage() {
        initComponents();
        
        states=AppState.getInstance();
        database=Database.getInstance();
        
        Thread background = new Thread(()->{
            try {
                wallpaperIndex = (int)(Math.random()*wallpaperLength);
                while (states.isRunning) {
                    backgroundLabel.setIcon(new ImageIcon(getClass().getResource("/images/background "+wallpaperIndex+".png")));
                    Thread.sleep(wallpaperTime);
                    wallpaperIndex = (wallpaperIndex+1)%wallpaperLength;
                }
                System.out.println("background thread ended");
            } catch (Exception e) {
                
            }
            System.out.println("Background thread of sample page ended");
        });
        //background.start();
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnProfileIcon = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        profileMenu = new components.ProfileMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new CustomJTable();
        jPanel2 = new javax.swing.JPanel();
        txtType = new javax.swing.JTextField();
        btnTypeGo = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnIdGo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCount = new javax.swing.JTextField();
        btnCountGo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        chooseData = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtGraph = new javax.swing.JButton();
        txtAllUsersGraph = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileSmall.png"))); // NOI18N
        btnProfileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileIconMouseClicked(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnProfileIcon)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfileIcon)
                            .addComponent(btnHome)
                            .addComponent(btnExit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 1400, 70));

        menuPanel.setOpaque(false);
        menuPanel.setLayout(new java.awt.CardLayout());

        blankPanel.setOpaque(false);

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        menuPanel.add(blankPanel, "card2");
        menuPanel.add(profileMenu, "card3");

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 120, 270, 320));

        table.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        table.setForeground(new java.awt.Color(50, 50, 50));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(32);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tableCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 1610, 570));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        txtType.setToolTipText("Delete products of specified type");

        btnTypeGo.setText("Go");
        btnTypeGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeGoActionPerformed(evt);
            }
        });

        txtId.setToolTipText("Delete product by id");

        btnIdGo.setText("Go");
        btnIdGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtType)
                        .addGap(18, 18, 18)
                        .addComponent(btnTypeGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIdGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtType)
                    .addComponent(btnTypeGo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId)
                    .addComponent(btnIdGo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 380, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Count", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        txtCount.setToolTipText("Count products of specified type");

        btnCountGo.setText("Go");
        btnCountGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCount, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCountGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCountGo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 390, 90));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        chooseData.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        chooseData.setForeground(new java.awt.Color(50, 50, 50));
        chooseData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Users", "Products" }));
        chooseData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseDataItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 110));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graphs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        txtGraph.setText("Go");
        txtGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGraphActionPerformed(evt);
            }
        });

        txtAllUsersGraph.setText("All Users");
        txtAllUsersGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllUsersGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAllUsersGraph))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGraph)
                    .addComponent(txtAllUsersGraph))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 390, 80));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background 1.png"))); // NOI18N
        backgroundLabel.setText("jLabel1");
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1701, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileIconMouseClicked
        if (!menuVisible) {
            setParentPanelTo(menuPanel,profileMenu);
            menuVisible=true;
        } else {
            setParentPanelTo(menuPanel,blankPanel);
            menuVisible=false;
        }
    }//GEN-LAST:event_btnProfileIconMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        MainWindow window=new MainWindow();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        JOptionPane.showMessageDialog(null,"Exiting");
        Application.closeApp();
    }//GEN-LAST:event_btnExitMouseClicked

    private void chooseDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseDataItemStateChanged
        int tableType = chooseData.getSelectedIndex();
        showData(tableType);
    }//GEN-LAST:event_chooseDataItemStateChanged

    private void btnTypeGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeGoActionPerformed
        Thread go = new Thread(()->{
            String delete=txtType.getText();
            database.dbQuery.deleteProductByType(delete);
            showData(1); // show products
        });
        go.start();
    }//GEN-LAST:event_btnTypeGoActionPerformed

    private void btnIdGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdGoActionPerformed
        Thread go = new Thread(()->{
            String delete=txtId.getText();
            database.dbQuery.deleteProductById(delete);
            showData(1); // show products
        });
        go.start();
    }//GEN-LAST:event_btnIdGoActionPerformed

    private void btnCountGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountGoActionPerformed
        Thread go = new Thread(()->{
            String count=txtCount.getText();
            int cnt=database.dbQuery.countProductByType(count);
            showData(1); // show products
            JOptionPane.showMessageDialog(null, cnt+"");
        });
        go.start();
    }//GEN-LAST:event_btnCountGoActionPerformed

    private void tableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableCaretPositionChanged
        tableValueChanged();
    }//GEN-LAST:event_tableCaretPositionChanged

    private void tablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablePropertyChange
        tableValueChanged();
    }//GEN-LAST:event_tablePropertyChange

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        tableValueChanged();
    }//GEN-LAST:event_tableMouseClicked

    private void txtGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraphActionPerformed
        Thread showGraph = new Thread(()->{
            ArrayList<Integer> stats=new ArrayList<>();
            String email=txtUser.getText();
            if (!Patterns.isValidEmail(email)) {
                JOptionPane.showMessageDialog(null, "Enter valid email");
                return;
            }
            for (int i=0;i<12;i++) {
                int tmp=database.dbQuery.getAllProductsUploadByUserInAMonthOfAYear(i+1, 2018, email).size();
                //tmp+=database.dbQuery.getAllProductsUploadByUserInAMonthOfAYear(i+1, 2018,getEmail1(email)).size();
                //tmp+=database.dbQuery.getAllProductsUploadByUserInAMonthOfAYear(i+1, 2018,getEmail2(email)).size();
                stats.add(tmp);
                System.out.println(stats);
            }
            Graph.createStat(stats);
        });
        showGraph.start();
        
        
        
    }//GEN-LAST:event_txtGraphActionPerformed

    private void txtAllUsersGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllUsersGraphActionPerformed
        String emails[]={"shreyasdobhal@gmail.com","kalyanprusty@gmail.com","prakharsrivastava@gmail.com","saarthakprakash@gmail.com","ayushgupta@gmail.com","priyanshusingh@gmail.com"};
        Thread showGraph = new Thread(()->{
            ArrayList<Integer> stats=new ArrayList<>();
            
            for (int i=0;i<emails.length;i++) {
                int tmp=database.dbQuery.getAllProductWithSellerId(emails[i]).size();
                tmp+=database.dbQuery.getAllProductWithSellerId(getEmail1(emails[i])).size();
                //tmp+=database.dbQuery.getAllProductWithSellerId(getEmail2(emails[i])).size();
                stats.add(tmp);
            }
            System.out.println(stats);
            Graph.createStat(emails,stats);
        });
        showGraph.start();
    }//GEN-LAST:event_txtAllUsersGraphActionPerformed
    
    private String getEmail1(String s) {
        try {
            return s.substring(0,s.indexOf('@'))+"_"+s.substring(s.indexOf('@')+1,s.indexOf('.'));
        } catch (Exception e) {
            return "";
        }
    }
    
    private String getEmail2(String s) {
        try {
            return s.substring(0,s.indexOf('@'))+" "+s.substring(s.indexOf('@')+1,s.indexOf('.'));
        } catch (Exception e) {
            return "";
        }
    }
    
    private void tableValueChanged() {
        try {
            String value=(String)table.getValueAt(table.getSelectedRow(), table.getSelectedColumn());
            System.out.println(value);
            txtUser.setText(value);
        } catch (Exception e) {
            
        }
    }
    
    private void showData(int tableType) {
        String tableInfo[][];
        if (tableType==1) {
            ArrayList<Product> products = database.dbQuery.getAllProduct();
            int size=products.size();
            tableInfo=new String[size][header[tableType].length];
            int index=0;
            for (Product product:products) {
                tableInfo[index][0]=product.productId;
                tableInfo[index][1]=product.type;
                tableInfo[index][2]=product.productName;
                tableInfo[index][3]=product.sellerId;
                if (product.buyerId.equals("null"))
                    tableInfo[index][4]="-";
                else
                    tableInfo[index][4]=product.buyerId;
                tableInfo[index][5]=product.dateOfUpload;
                if (product.dateOfSelling.equals("null"))
                    tableInfo[index][6]="-";
                else
                    tableInfo[index][6]=product.dateOfSelling;
                if (product.discount.equals("null"))
                    tableInfo[index][7]="-";
                else
                    tableInfo[index][7]=product.discount;
                tableInfo[index][8]=product.cost+"";
                if (product.expiry.equals("null"))
                    tableInfo[index][9]="-";
                else
                    tableInfo[index][9]=product.expiry;
                index++;
            }
        } else {
            ArrayList<User> users = database.dbQuery.getAllUsers();
            int size=users.size();
            tableInfo=new String[size][header[tableType].length];
            int index=0;
            for (User user:users) {
                tableInfo[index][0]=user.emailId;
                tableInfo[index][1]=user.name;
                tableInfo[index][2]=user.location;
                tableInfo[index][3]=user.phoneNumber;
                tableInfo[index][4]=user.rating+"";
                tableInfo[index][5]=Boolean.toString(user.isAdmin);
                index++;
            }
            
        }
        setTable(tableInfo, header[tableType]);
    }
    
    private void setTable(String data[][],String header[]) {
        table.setModel(new javax.swing.table.DefaultTableModel(data,header));
    }
    
    private void setParentPanelTo(JPanel parent,JPanel panel) {
        //menuPanel.removeAll();
        parent.removeAll();
        parent.add(panel);
        parent.repaint();
        parent.revalidate();
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton btnCountGo;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnIdGo;
    private javax.swing.JLabel btnProfileIcon;
    private javax.swing.JButton btnTypeGo;
    private javax.swing.JComboBox chooseData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    private components.ProfileMenu profileMenu;
    private javax.swing.JTable table;
    private javax.swing.JButton txtAllUsersGraph;
    private javax.swing.JTextField txtCount;
    private javax.swing.JButton txtGraph;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
