/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickpick;

import components.ProductPanel;
import database.Database;
import database.Heap;
import database.Product;
import database.User;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Queue;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Application;
import utility.Patterns;

/**
 *
 * @author Shreyas
 */
public class EditProfilePage extends javax.swing.JFrame {

    private AppState states;
    private Database database;
    public User user;
    private int wallpaperTime = 3*1000;
    private int wallpaperIndex = 0;
    private int wallpaperLength = 4;
    private boolean menuVisible = false;
    
    public EditProfilePage() {
        initComponents();
        
        states=AppState.getInstance();
        database=Database.getInstance();
        
        Thread background = new Thread(()->{
            try {
                wallpaperIndex = (int)(Math.random()*wallpaperLength);
                while (states.isRunning) {
                    backgroundLabel.setIcon(new ImageIcon(getClass().getResource("/images/background "+wallpaperIndex+".png")));
                    Thread.sleep(wallpaperTime);
                    wallpaperIndex = (wallpaperIndex+1)%wallpaperLength;
                }
                System.out.println("background thread ended");
            } catch (Exception e) {
                
            }
            System.out.println("Background thread of edit profile page ended");
        });
        //background.start();
        
        Thread loadUser = new Thread(()->{
            user=states.user;
            txtName.setText(user.name);
            txtOldPassword.setText("");
            txtNewPassword.setText("");
            txtConfirmPassword.setText("");
            txtNumber.setText(user.phoneNumber);
            txtLocation.setText(user.location);
        });
        loadUser.start();
        
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnProfileIcon = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        profileMenu = new components.ProfileMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtOldPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileSmall.png"))); // NOI18N
        btnProfileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileIconMouseClicked(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1110, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnProfileIcon)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfileIcon)
                            .addComponent(btnHome)
                            .addComponent(btnExit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 1400, 70));

        menuPanel.setOpaque(false);
        menuPanel.setLayout(new java.awt.CardLayout());

        blankPanel.setOpaque(false);

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        menuPanel.add(blankPanel, "card2");
        menuPanel.add(profileMenu, "card3");

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 120, 270, 320));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 22), new java.awt.Color(50, 50, 50))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setText("Personal Details ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 35));

        txtLocation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(50, 50, 50));
        jPanel2.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 270, 35));

        txtOldPassword.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtOldPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtOldPassword.setToolTipText("");
        jPanel2.add(txtOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 280, 41));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setText("Old Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 35));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setText("Location");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 160, 35));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 70, 70));
        jLabel5.setText("Confirm Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 35));

        txtNewPassword.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtNewPassword.setToolTipText("");
        jPanel2.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 280, 41));

        txtConfirmPassword.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtConfirmPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtConfirmPassword.setToolTipText("");
        jPanel2.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 280, 41));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 543, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 352, 540, 10));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(50, 50, 50));
        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 98, 76, 35));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setText("New Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 35));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 70));
        jLabel9.setText("Contact Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 35));

        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(50, 50, 50));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 100, 270, 35));

        txtNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(50, 50, 50));
        jPanel2.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 270, 35));

        btnCancel.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(50, 50, 50));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 160, 40));

        btnOk.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnOk.setForeground(new java.awt.Color(50, 50, 50));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel2.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 590, 680));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background 1.png"))); // NOI18N
        backgroundLabel.setText("jLabel1");
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1701, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileIconMouseClicked
        if (!menuVisible) {
            setParentPanelTo(menuPanel,profileMenu);
            menuVisible=true;
        } else {
            setParentPanelTo(menuPanel,blankPanel);
            menuVisible=false;
        }
    }//GEN-LAST:event_btnProfileIconMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        MainWindow window=new MainWindow();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MainWindow window=new MainWindow();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO: edit user info
        boolean flag=false;
        String message="Changes saved";
        String str=new String(txtOldPassword.getPassword());
        String name="",password=user.password,location="",phone="";
        if (user.password.equals(str)) {
            flag=true;
            name=txtName.getText();
            password=user.password;
            String newPassword=new String(txtNewPassword.getPassword());
            String confirmPassword=new String(txtConfirmPassword.getPassword());
            
            if (newPassword.equals(confirmPassword)) {
                password=newPassword;
            } else {
                message="Password do not match";
                flag=false;
            }
            
            phone=txtNumber.getText();
            location=txtLocation.getText();
            
            if (!Patterns.isValidContact(phone)) {
                if (!message.equals("Password not changed")) {
                    message="Phone number invalid";
                    flag=false;
                }
            }
            
            // Do query
            
        } else {
            message="Password incorrect";
        }
        
        if (flag) {
            states.user.name=name;
            states.user.password=password;
            states.user.location=location;
            states.user.phoneNumber=phone;
            database.dbQuery.updateUser(states.user.emailId, name, password, location, phone);
            JOptionPane.showMessageDialog(null, message);
            MainWindow window=new MainWindow();
            Application.goToFrame(window);
        } else {
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        JOptionPane.showMessageDialog(null,"Exiting");
        Application.closeApp();
    }//GEN-LAST:event_btnExitMouseClicked
    
    private void setParentPanelTo(JPanel parent,JPanel panel) {
        //menuPanel.removeAll();
        parent.removeAll();
        parent.add(panel);
        parent.repaint();
        parent.revalidate();
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel btnProfileIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menuPanel;
    private components.ProfileMenu profileMenu;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
