/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickpick;

import components.ProductPanel;
import database.Database;
import database.Heap;
import database.Product;
import database.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Queue;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Application;
import utility.Patterns;
import utility.Time;

/**
 *
 * @author Shreyas
 */
public class ProductSellPage extends javax.swing.JFrame {

    private AppState states;
    private Database database;
    public User user;
    private int wallpaperTime = 3*1000;
    private int wallpaperIndex = 0;
    private int wallpaperLength = 4;
    private boolean menuVisible = false;
    
    private String defaultDir="C:\\Users\\Shreyas\\Desktop";
    private String imageFilePath="";
    private String imageFileName="";
    public ProductSellPage() {
        initComponents();
        
        states=AppState.getInstance();
        database=Database.getInstance();
        
        user=states.user;
        
        Thread background = new Thread(()->{
            try {
                wallpaperIndex = (int)(Math.random()*wallpaperLength);
                while (states.isRunning) {
                    backgroundLabel.setIcon(new ImageIcon(getClass().getResource("/images/background "+wallpaperIndex+".png")));
                    Thread.sleep(wallpaperTime);
                    wallpaperIndex = (wallpaperIndex+1)%wallpaperLength;
                }
                System.out.println("background thread ended");
            } catch (Exception e) {
                
            }
            System.out.println("Background thread of product sell page ended");
        });
        //background.start();
        
       
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnProfileIcon = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        profileMenu = new components.ProfileMenu();
        jPanel2 = new javax.swing.JPanel();
        imgDisplay = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        txtProductNameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescriptionField = new javax.swing.JTextArea();
        chooseCategory = new javax.swing.JComboBox();
        chooseType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTagField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkExpiry = new javax.swing.JCheckBox();
        chkDiscount = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtPriceField = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        dateExpiry = new com.toedter.calendar.JDateChooser();
        dateDiscount = new com.toedter.calendar.JDateChooser();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileSmall.png"))); // NOI18N
        btnProfileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileIconMouseClicked(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1110, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnProfileIcon)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfileIcon)
                            .addComponent(btnHome)
                            .addComponent(btnExit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 1400, 70));

        menuPanel.setOpaque(false);
        menuPanel.setLayout(new java.awt.CardLayout());

        blankPanel.setOpaque(false);

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        menuPanel.add(blankPanel, "card2");
        menuPanel.add(profileMenu, "card3");

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 120, 270, 320));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        imgDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeHolder.png"))); // NOI18N

        jLabel0.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel0.setForeground(new java.awt.Color(50, 50, 50));
        jLabel0.setText("Product Name : ");

        btnUpload.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(50, 50, 50));
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtProductNameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtProductNameField.setForeground(new java.awt.Color(60, 60, 60));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(50, 50, 50));
        jLabel10.setText("Description");

        txtDescriptionField.setColumns(20);
        txtDescriptionField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescriptionField.setForeground(new java.awt.Color(60, 60, 60));
        txtDescriptionField.setRows(5);
        jScrollPane1.setViewportView(txtDescriptionField);

        chooseCategory.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        chooseCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electronics", "Mobile/Computers", "Fashion", "Home/Kitchen", "Sports", "Stationary" }));
        chooseCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseCategoryItemStateChanged(evt);
            }
        });

        chooseType.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        chooseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TV", "Headphone", "Speaker", "Camera", "Refrigerator", "Washing Machine", "AC", "Other" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setText("List of tags (comma separated)");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 50, 50));
        jLabel5.setText("Select Category and Type");

        txtTagField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTagField.setForeground(new java.awt.Color(60, 60, 60));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 50, 50));
        jLabel6.setText("Limited Discount/Offer (*optional)");

        txtDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(60, 60, 60));
        txtDiscount.setText("0");
        txtDiscount.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel3.setText("%");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(50, 50, 50));
        jLabel7.setText("Discount Validity");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(50, 50, 50));
        jLabel8.setText("Expiry / Best before");

        chkExpiry.setBackground(new java.awt.Color(250, 250, 250));
        chkExpiry.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        chkExpiry.setForeground(new java.awt.Color(50, 50, 50));
        chkExpiry.setText(" Has expiry or best before date");
        chkExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExpiryActionPerformed(evt);
            }
        });

        chkDiscount.setBackground(new java.awt.Color(250, 250, 250));
        chkDiscount.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        chkDiscount.setForeground(new java.awt.Color(50, 50, 50));
        chkDiscount.setText(" Apply discount for buyers");
        chkDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDiscountActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(50, 50, 50));
        jLabel9.setText("Price (in Rs)");

        txtPriceField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPriceField.setForeground(new java.awt.Color(60, 60, 60));

        btnDone.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        btnDone.setForeground(new java.awt.Color(50, 50, 50));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        dateExpiry.setForeground(new java.awt.Color(50, 50, 50));
        dateExpiry.setDateFormatString("dd/MM/yyyy");
        dateExpiry.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        dateDiscount.setForeground(new java.awt.Color(50, 50, 50));
        dateDiscount.setDateFormatString("dd/MM/yyyy");
        dateDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(imgDisplay)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProductNameField))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(chooseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chooseType, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnUpload)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(89, 89, 89))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTagField, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(dateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(btnDone))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkDiscount)
                        .addGap(449, 449, 449)
                        .addComponent(chkExpiry)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel0)
                            .addComponent(txtProductNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addComponent(imgDisplay))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUpload))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTagField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addComponent(dateDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDiscount)
                    .addComponent(chkExpiry))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 990, 830));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background 1.png"))); // NOI18N
        backgroundLabel.setText("jLabel1");
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1701, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileIconMouseClicked
        if (!menuVisible) {
            setParentPanelTo(menuPanel,profileMenu);
            menuVisible=true;
        } else {
            setParentPanelTo(menuPanel,blankPanel);
            menuVisible=false;
        }
    }//GEN-LAST:event_btnProfileIconMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        MainWindow window=new MainWindow();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void chooseCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseCategoryItemStateChanged
        chooseType.setModel(new DefaultComboBoxModel(Database.productTypes[chooseCategory.getSelectedIndex()]));
    }//GEN-LAST:event_chooseCategoryItemStateChanged

    private void chkDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDiscountActionPerformed
        if (chkDiscount.isSelected()) {
            txtDiscount.setEnabled(true);
            dateDiscount.setEnabled(true);
        } else {
            txtDiscount.setEnabled(false);
            dateDiscount.setEnabled(false);
        }
    }//GEN-LAST:event_chkDiscountActionPerformed

    private void chkExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExpiryActionPerformed
        if (chkExpiry.isSelected()) {
            dateExpiry.setEnabled(true);
        } else {
            dateExpiry.setEnabled(false);
        }
    }//GEN-LAST:event_chkExpiryActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String productName=txtProductNameField.getText().trim();
        String description=txtDescriptionField.getText().trim();
        String category=((String)chooseCategory.getSelectedItem()).trim();
        String type=((String)chooseType.getSelectedItem()).trim();
        String tags=txtTagField.getText().trim();
        String discount="null";
        String duration="null";
        String expiry="null";
        String price=txtPriceField.getText().trim();
        
        if (!Patterns.isValidNumber(price)) {
            JOptionPane.showMessageDialog(null,"Invalid Price");
            return;
        }
        
        int cost=0;
        
        if (chkDiscount.isSelected()) {
            discount=txtDiscount.getText().trim();
        }
        
        
        // Checking for validity
        try {
            if (productName.isEmpty()) {
                txtProductNameField.setBorder(BorderFactory.createLineBorder(Color.red,2));
                return;
            } else {
                txtProductNameField.setBorder(BorderFactory.createLineBorder(Color.black,0));
            }
            
            if (description.isEmpty()) {
                txtDescriptionField.setBorder(BorderFactory.createLineBorder(Color.red,2));
                return;
            } else {
                txtDescriptionField.setBorder(BorderFactory.createLineBorder(Color.black,0));
            }
            
            if (tags.isEmpty()) {
                txtTagField.setBorder(BorderFactory.createLineBorder(Color.red,2));
                return;
            } else {
                txtTagField.setBorder(BorderFactory.createLineBorder(Color.black,0));
            }
            
            if (chkDiscount.isSelected()) {
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyy");
                duration=df.format(dateDiscount.getDate());
            }
            if (chkExpiry.isSelected()) {
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyy");
                expiry=df.format(dateExpiry.getDate());
            }
            
            if (chkDiscount.isSelected())
                Integer.valueOf(discount);
            cost=Integer.valueOf(price);
            
        } catch (Exception e) {
            txtDiscount.setText("");
            txtPriceField.setText("");
            return;
        }
        
        
        // Checking done
        // TODO: include image
        System.out.println(user);
        System.out.println(user.emailId);
        
        Product product=new Product("@id_thatDoesntmatter",productName,description,cost,user.emailId,user.name,Time.getCurrentDate(),"null","null",tags,type,"null",discount,duration,expiry,imageFilePath);
        database.dbQuery.insertProduct(product,imageFilePath,imageFileName);
        
        JOptionPane.showMessageDialog(null,"Product uploaded");
        
        MainWindow window=new MainWindow();
        Application.goToFrame(window);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(defaultDir));
        
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                imageFilePath=chooser.getSelectedFile().getPath();
                imageFileName=chooser.getSelectedFile().getName();//+Time.getTimeForName();
                
                System.out.println("file path "+imageFilePath);
                System.out.println("file name "+imageFileName);
                
                setThumbnail(imgDisplay,imageFilePath,400,400);
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        
    
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        JOptionPane.showMessageDialog(null,"Exiting");
        Application.closeApp();
    }//GEN-LAST:event_btnExitMouseClicked
    // public Product(String productId,String productName,String description,int cost,String sellerId,String sellerName,String dateOfUpload,
    // String buyerId,String buyerName,String tags,String type)
    
    private void setParentPanelTo(JPanel parent,JPanel panel) {
        //menuPanel.removeAll();
        parent.removeAll();
        parent.add(panel);
        parent.repaint();
        parent.revalidate();
    }
    
    public void setThumbnail(JLabel label,String URL,int w,int h) {
        
        Thread loader = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    String url=URL;
                    BufferedImage brImg = ImageIO.read(new URL("file:///"+url));
                    BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
                    Graphics2D g2 = resizedImg.createGraphics();
                    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g2.drawImage(brImg, 0, 0, w, h, null);
                    g2.dispose();
                    label.setIcon(new ImageIcon(resizedImg)); 
                }
                catch (Exception e) {
                    System.out.println("error");
                    e.printStackTrace();
                }
            }
        });
        loader.start();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSellPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnProfileIcon;
    private javax.swing.JButton btnUpload;
    private javax.swing.JCheckBox chkDiscount;
    private javax.swing.JCheckBox chkExpiry;
    private javax.swing.JComboBox chooseCategory;
    private javax.swing.JComboBox chooseType;
    private com.toedter.calendar.JDateChooser dateDiscount;
    private com.toedter.calendar.JDateChooser dateExpiry;
    private javax.swing.JLabel imgDisplay;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    private components.ProfileMenu profileMenu;
    private javax.swing.JTextArea txtDescriptionField;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPriceField;
    private javax.swing.JTextField txtProductNameField;
    private javax.swing.JTextField txtTagField;
    // End of variables declaration//GEN-END:variables
}
